FROM node:22.22-alpine

# Set working directory
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn install; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  else echo "Lockfile not found." && yarn install; \
  fi

# Copy the rest of the application
COPY . .

# Disable telemetry during development
ENV NEXT_TELEMETRY_DISABLED 1

# Expose Next.js default port
EXPOSE 3000

# Start the development server
CMD ["yarn", "next:dev"]
